version: "3.7"

services:
    ecomerce-backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        networks:
            - app-ecomer

networks:
    app-ecomer:
        driver: bridge